docs/vite.config.ts, package.json, yarn.lock
Added GitHub flavoured markdown plugin
=> GitHub flavoured markdown plugin

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/blui-pr-actions.yml
add blui labels and pull request template
=> Use blui labels reusable workflow

.github/dependabot.yml, docs/index.html
=> Set up dependabot for RN Dev Docs

README.md, docs/README.md
added Readme for monorepo and docs project
=> BLUI 5745 update readme

docs/src/componentDocs/MobileStepper/markdown/MobileStepperExamples.mdx
Fixes #5677
- Add Example Docs for MobileStepper component
-
-
=> Add Example Docs for MobileStepper component

docs/src/componentDocs/IconSwitch/markdown/IconSwitchExamples.mdx
Fixes #5662
- Add Example docs for Iconswitch component
-
-
-
=> Add Example docs for Iconswitch component

.github/workflows/blui-ci.yml, docs/public/404.html, docs/src/componentDocs/InfoListItem/markdown/InfoListItemExamples.mdx, package.json
Fixes BLUI-5620.
- add blui-ci github workflow
- NOTE - blui ci file has prettier & lint commented out and is not running (this needs setup using prettier from brightlayer-ui and there are a hand full of lint warnings)
-
-
-
-
=> Add blui ci github workflow

.github/workflows/blui-ci.yml
Fixes BLUI-5761.
- add prepended flag for folder path. 
- https://github.com/JamesIves/github-pages-deploy-action/tree/v4/?tab=readme-ov-file#required-setup
-
-
-
-
=> Use absolute file path for deploy dist docs

docs/index.html, docs/public/404.html
=> update index & 404

docs/src/components/layout/SharedAppBar.tsx, docs/src/components/pages/HomePage.tsx, docs/src/main.tsx
=> Update base name to use base url

docs/src/components/pages/HomePage.tsx
=> update url image to be included with build

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, CODEOWNERS
Fixes BLUI-5786.
- add issue templates & code owners
-
-
-
-
-
=> Add issue templates & code owners

package.json, yarn.lock
=> Use RN comp library 8.0.4-beta

docs/src/componentDocs/IconSwitch/examples/IconSwitch.tsx, docs/src/componentDocs/IconSwitch/examples/IconSwitchExample.tsx, docs/src/componentDocs/IconSwitch/examples/IconSwitchWithIcon.tsx, docs/src/componentDocs/IconSwitch/examples/IconSwitchWithIconExample.tsx, docs/src/componentDocs/IconSwitch/markdown/IconSwitchExamples.mdx
Fixes #5797
-Convert images to live RN code (using react-native-web)
-Remove unused image assets
-Convert markdown code blocks to PrismJS code blocks
-Use PrismJS to highlight targeted lines in the code example blocks
-Include buttons to copy to clipboard and view full github source
-
-
-
=> Convert IconSwitch to live code examples

docs/src/componentDocs/Grade/examples/GradeCustomColor.tsx, docs/src/componentDocs/Grade/examples/GradeCustomColorExample.tsx
Fixes # .
- Fixed color code and indentations of Grade custom color example
-
-
=> fix grade custom color

docs/src/componentDocs/EmptyState/examples/EmptyStateWithActions.tsx, docs/src/componentDocs/EmptyState/examples/EmptyStateWithActionsExample.tsx, docs/src/componentDocs/EmptyState/examples/EmptyStateWithContent.tsx, docs/src/componentDocs/EmptyState/examples/EmptyStateWithContentExample.tsx, docs/src/componentDocs/EmptyState/examples/EmptyStateWithDescription.tsx, docs/src/componentDocs/EmptyState/examples/EmptyStateWithDescriptionExample.tsx, docs/src/componentDocs/EmptyState/markdown/EmptyStateExamples.mdx
Fixes #5659
-Convert images to live RN code (using react-native-web)
-Remove unused image assets
-Convert markdown code blocks to PrismJS code blocks
-Use PrismJS to highlight targeted lines in the code example blocks
-Include buttons to copy to clipboard and view full github source
-
-
-
=> Add Example Docs for EmptyState component

docs/src/componentDocs/Header/examples/HeaderWithBackground.tsx, docs/src/componentDocs/Header/examples/HeaderWithBackgroundExample.tsx
Fixes # .
- fix warning Type 'string' is not assignable to type 'ImageSourcePropType
-
-
-
-
-
=> Fix type script warning

apps/showcase/src/app/App.tsx, apps/showcase/src/main-web.tsx, docs/src/componentDocs/CollapsibleHeaderLayout/examples/CollapsibleHeaderLayoutExample.tsx, package.json
- Added linting script for showcase
- yarn lint
- yarn lint:fix
- yarn showcase-lint
- yarn showcase-lint:fix
=> Added linting scripts for showcase

docs/src/componentDocs/CollapsibleHeaderLayout/examples/CollapsibleHeaderLayoutExample.tsx, docs/src/componentDocs/DrawerSubheader/examples/DrawerSubheaderExample.tsx, docs/src/components/InfoCard.tsx
Fixes # . remove default props
-
-
-
-
-
-
=> remove default props

.github/workflows/blui-ci.yml
Fixes BLUI-5832.
- add prettier and lint checks to job
- open PR once this is merged. https://github.com/etn-ccis/blui-react-native/pull/93
-
-
-
-
=> Add prettier & lint to blui-ci job

docs/src/componentDocs/Chip/markdown/ChipAPIDocs.mdx, docs/src/componentDocs/CollapsibleHeaderLayout/markdown/CollapsibleHeaderLayoutAPIDocs.mdx, docs/src/componentDocs/EmptyState/markdown/EmptyStateAPIDocs.mdx, docs/src/componentDocs/Grade/markdown/GradeAPIDocs.mdx, docs/src/componentDocs/Header/markdown/HeaderAPIDocs.mdx, docs/src/componentDocs/InfoListItem/markdown/InfoListItemAPIDocs.mdx, docs/src/componentDocs/ScoreCard/markdown/ScoreCardAPIDocs.mdx, docs/src/componentDocs/UserMenu/markdown/UserMenuAPIDocs.mdx
Fixes # .
- Placeholder Removed
-
-
-
-
-
=> Removed placeholder from react native API doc

docs/src/componentDocs/EmptyState/examples/EmptyStateWithActionsExample.tsx, docs/src/componentDocs/EmptyState/examples/EmptyStateWithContentExample.tsx, docs/src/componentDocs/EmptyState/examples/EmptyStateWithDescriptionExample.tsx, docs/src/componentDocs/InfoListItem/examples/InfoListItemClickableExample.tsx, docs/src/componentDocs/InfoListItem/examples/InfoListItemContentExample.tsx, docs/src/componentDocs/InfoListItem/examples/InfoListItemExample.tsx, docs/src/componentDocs/InfoListItem/examples/InfoListItemMultipleExample.tsx, docs/src/componentDocs/InfoListItem/examples/InfoListItemStatusExample.tsx, docs/src/componentDocs/UserMenu/examples/UserMenuToolbarExample.tsx, docs/src/utils/constants.ts
Fixes #BLUI-5826 .
- Added DEMO_WIDTH constant and updated styles for few components
-
-
-
=> Synchronize Demo Widths

docs/src/__configuration__/navigationMenu.tsx, docs/src/componentDocs/Chip/markdown/ChipAPIDocs.mdx, docs/src/componentDocs/Chip/playground/PlaygroundPage.tsx, docs/src/componentDocs/Chip/playground/index.tsx
=> Added playground for Chip component

docs/src/__configuration__/navigationMenu.tsx, docs/src/componentDocs/Hero/playground/index.tsx, docs/src/componentDocs/Hero/playground/playgroundPage.tsx, docs/src/utils/utilities.tsx
=> Added playground for Hero component

docs/src/__configuration__/navigationMenu.tsx, docs/src/componentDocs/ListItemTag/playground/index.tsx, docs/src/componentDocs/ListItemTag/playground/playgroundPage.tsx
Fixes # .
Changes proposed in this Pull Request:
-
-
-
=> Added playground for List Item Tag component

docs/src/__configuration__/navigationMenu.tsx, docs/src/componentDocs/EmptyState/playground/PlaygroundPage.tsx, docs/src/componentDocs/EmptyState/playground/index.tsx
=> Added playground for EmptyState

docs/src/componentDocs/DrawerHeader/playground/PlaygroundPage.tsx
Fixes # .
- remove playground divider prop option for drawer header
-
-
-
-
-
=> Remove divider prop from playground

docs/src/components/ComponentPreviewTabs.tsx
Fixes BLUI-5883, BLUI-5878.
- hide playground tabs
-
-
-
-
-
=> Hide playground drawer subheader & footer

docs/src/__configuration__/navigationMenu.tsx, docs/src/componentDocs/Drawer/playground/sharedPropsConfig.ts, docs/src/componentDocs/DrawerNavGroup/playground/PlaygroundPage.tsx, docs/src/componentDocs/DrawerNavGroup/playground/index.tsx
Fixes BLUI-5880.
- Add drawer nav group playground
-
-
-
-
=> Add drawer nav group playground

docs/src/__configuration__/navigationMenu.tsx, docs/src/componentDocs/DrawerNavItem/playground/PlaygroundPage.tsx, docs/src/componentDocs/DrawerNavItem/playground/index.tsx
Fixes BLUI-5881.
- add drawer nav item playground
-
-
-
-
=> Add drawer nav item playground

docs/src/__configuration__/navigationMenu.tsx, docs/src/componentDocs/UserMenu/playground/PlaygroundPage.tsx, docs/src/componentDocs/UserMenu/playground/index.tsx
Fixes BLUI-5901.
- add user menu playground
-
-
-
-
=> Add user menu playground

docs/src/__configuration__/navigationMenu.tsx, docs/src/componentDocs/InfoListItem/playground/index.tsx, docs/src/componentDocs/InfoListItem/playground/playgroundPage.tsx, docs/src/utils/utilities.tsx
=> Added playground for Info List Item

docs/src/__configuration__/navigationMenu.tsx, docs/src/componentDocs/ChannelValue/playground/PlaygroundPage.tsx, docs/src/componentDocs/MobileStepper/examples/MobileStepperDotVariantExample.tsx, docs/src/componentDocs/MobileStepper/examples/MobileStepperProgressVariantExample.tsx, docs/src/componentDocs/MobileStepper/examples/MobileStepperTextVariantExample.tsx, docs/src/componentDocs/MobileStepper/playground/PlaygroundPage.tsx, docs/src/componentDocs/MobileStepper/playground/index.ts
Fixes #BLUI-5897 .
- Add Mobile Stepper playground
-
-
=> Integrate Playground for Mobile Stepper

docs/src/__configuration__/navigationMenu.tsx, docs/src/componentDocs/CollapsibleHeaderLayout/playground/PlaygroundPage.tsx, docs/src/componentDocs/CollapsibleHeaderLayout/playground/index.tsx
Fixes BLUI-6002.
- add collapsible header playground
-
-
-
-
=> Add collapsible header playground

.github/workflows/blui-ci.yml
Fixes # .
- revert changes from dependabot update
-
-
-
-
=> revert to version 3 actions/download-artifact

docs/src/componentDocs/Chip/examples/Chip.tsx, docs/src/componentDocs/Chip/examples/ChipSelect.tsx, docs/src/componentDocs/Chip/examples/ChipWithIcon.tsx, docs/src/componentDocs/CollapsibleHeaderLayout/examples/CollapsibleHeaderLayout.tsx, docs/src/componentDocs/Grade/examples/GradeCustomColor.tsx, docs/src/componentDocs/Header/examples/HeaderWithActions.tsx, docs/src/componentDocs/InfoListItem/examples/InfoListItem.tsx, docs/src/componentDocs/InfoListItem/examples/InfoListItemClickable.tsx, docs/src/componentDocs/InfoListItem/examples/InfoListItemContent.tsx, docs/src/componentDocs/InfoListItem/examples/InfoListItemMultiple.tsx, docs/src/componentDocs/InfoListItem/examples/InfoListItemStatus.tsx, docs/src/componentDocs/ScoreCard/examples/ScoreCard.tsx, docs/src/componentDocs/ScoreCard/examples/ScoreCardAdjustBadge.tsx, docs/src/componentDocs/ScoreCard/examples/ScoreCardWithActions.tsx, docs/src/componentDocs/ScoreCard/examples/ScoreCardWithBadge.tsx, docs/src/components/ComponentPreviewTabs.tsx
Fixes BLUI-6005. Items found during test
- update links to github examples
- hide playground tab for overline & icons
-
-
-
-
=> Component docs update

docs/src/__configuration__/listOfAllBluiReactPackages.ts
Fixes # BLUI-6297
- Removed blui-cli from list of packages
-
- 
-
-
=> Removed blui-cli from list of packages

README.md
=> Updated github links for included packages section in Readme

.github/workflows/blui-ci.yml
Fixes # BLUI-6549
- Updated gh actions version to v4
-
-
-
=> Updated gh actions version to v4

packages/blui-react-native-progress-icons/package.json, yarn.lock
- jest version upgraded for blui-progress-icon for unit testing
-
-
-
-
-
=> Added version upgrade of jest for blui-progress-icon unit testing

.github/workflows/blui-ci.yml, .github/workflows/blui-publish-auth-workflow.yml, .github/workflows/blui-publish-components.yml, .github/workflows/blui-publish-progress-icons.yml, .github/workflows/blui-publish-templates.yml, .github/workflows/blui-publish-themes.yml, packages/progress-icons/package.json, packages/themes/package.json
Fixes BLUI-6559.
Part 1 of 2 (additional PR will cover hot reloads)
- add reusable publish workflows for each package
- update publish in scripts
- update main entry points
-
-
-
=> Add publish reusable workflows

.github/workflows/blui-ci.yml, examples/showcase/src/actions/RegistrationUIActions.tsx, examples/showcase/src/contexts/AppContextProvider.tsx, examples/showcase/src/store/local-storage.ts, package.json, packages/auth-workflows/package.json, packages/cli-templates/authentication-typescript/package.json, packages/cli-templates/blank-typescript/package.json, packages/cli-templates/routing-typescript/package.json, packages/component-library/package.json, packages/progress-icons/package.json, packages/themes/package.json, yarn.lock
Fixes BLUI-6559
- test publish alpha for all packages
- add template packages to root package.json
-
-
-
-
=> Test alpha publish for packages

examples/showcase/src/actions/AuthUIActions.tsx, examples/showcase/src/actions/RegistrationUIActions.tsx, examples/showcase/src/contexts/AppContextProvider.tsx, examples/showcase/src/store/local-storage.ts
- Fixed lint and prettier issues for registration and auth UI actions
-
-
-
-
-
=> Fixed prettier and lint issues

examples/showcase/package.json, packages/auth-workflows/package.json, packages/component-library/package.json, packages/progress-icons/package.json, packages/themes/package.json, yarn.lock
Fixes BLUI-6559
- update package.json files to use publishConfig for publishing packages
- use main entry for local development that points to dist/index
- re-test publish with updated publishConfig entries
- update showcase  "@types/react": "^19.0.0" to use "@types/react": "^18.3.9"
to remedy the type errors
- clone fresh copy of repo and `git checkout feature/blui-6559-publish-config`
- run `yarn && yarn build:all`
- cd showcase run `npx react-native start`
- open second terminal run `yarn android` or `yarn ios` in showcase
- stop showcase
- verify auth workflow dist includes assets & meta data (package.json, readme, licenses...)
- cd packages/auth-workflows/dist
- run `npm publish --dry-run` (verify publish dry-run content)
-
- verify component-library dist includes meta data …
=> Use publishConfig for publish package and main for monorepo

.github/workflows/blui-ci.yml, packages/progress-icons/jest.config.js, packages/progress-icons/package.json
Fixes BLUI-6559
- add coverage config and test report for progress icons
-
-
-
https://app.codecov.io/gh/etn-ccis/blui-react-native/tree/feature%2Fblui-6559-add-progress-coverage/packages
-
=> add coverage and report for progress icons

examples/showcase/src/actions/AuthUIActions.tsx, examples/showcase/src/actions/RegistrationUIActions.tsx
=> commented the API call and returned the action with some timeout

packages/component-library/src/core/Header/HeaderNavigationIcon.tsx
Fixes # BLUI-6729 #162 
-Removed margin top from header naviagtion icon
- 
- cd docs
- yarn start
- Navigate to Header-->Playground
- Toggle on `searchableConfig`
- Click on search icon
-
=> Removed margin top from header naviagtion icon

docs/src/componentDocs/DrawerBody/examples/BasicDrawerBodyExample.tsx, docs/src/componentDocs/DrawerHeader/playground/PlaygroundPage.tsx, docs/src/componentDocs/DrawerNavGroup/playground/PlaygroundPage.tsx, docs/src/componentDocs/DrawerNavItem/examples/DrawerNavItemExample.tsx, docs/src/componentDocs/DrawerNavItem/examples/NestedNavItemExample.tsx, docs/src/componentDocs/DrawerNavItem/examples/SelectingANavItemExample.tsx, docs/src/componentDocs/DrawerNavItem/playground/PlaygroundPage.tsx, docs/src/componentDocs/DrawerSubheader/examples/DrawerSubheaderExample.tsx, docs/src/componentDocs/DrawerSubheader/examples/InteractiveDrawerSubheaderExample.tsx
Fixes # .
https://github.com/etn-ccis/blui-react-native/issues/160
- Font color change for Drawer
-
-
**Before**
**After**
- cd Docs -> yarn install -> yarn start
-
=> Fixed Drawer font color issue by adding itemFontColor prop

examples/showcase/jest.config.js, examples/workflow/jest.config.js, examples/workflow/jestSetupFile.js, package.json, packages/auth-workflows/jest.config.cjs, packages/auth-workflows/package.json, packages/auth-workflows/src/__tests__/screens/CreatePasswordScreen.test.tsx, packages/auth-workflows/src/__tests__/screens/EulaScreen.test.tsx, packages/auth-workflows/src/__tests__/screens/ForgotPasswordScreen.test.tsx, packages/auth-workflows/src/__tests__/screens/ForgotPasswordScreenBase.test.tsx, packages/auth-workflows/src/__tests__/screens/LoginScreen.test.tsx, packages/auth-workflows/src/__tests__/screens/VerifyCodeScreenBase.test.tsx, packages/auth-workflows/tsconfig.json, packages/auth-workflows/yarn.lock, packages/component-library/babel.config.cjs, packages/component-library/jest.config.cjs, packages/component-library/src/core/Chip/Chip.tsx, packages/component-library/src/core/Chip/__snapshots__/Chip.test.tsx.snap, packages/component-library/src/core/CollapsableHeaderLayout/CollapsableHeaderLayout.test.tsx, packages/component-library/src/core/HeroBanner/HeroBanner.test.tsx, packages/component-library/src/core/InfoListItem/InfoListItem.test.tsx, packages/component-library/src/core/MobileStepper/MobileStepper.test.tsx, packages/component-library/src/core/__hooks__/usePrevious.tsx, packages/component-library/tsconfig.json
Fixes # .
- updated the jest config to run the testcases
-
-
-
-
-
=> fix the unit test configuration in RN monorepo

docs/src/componentDocs/Drawer/examples/CustomizableDrawerExample.tsx, docs/src/componentDocs/Drawer/examples/DrawerExample.tsx, docs/src/componentDocs/DrawerFooter/examples/DrawerFooterExample.tsx, docs/src/componentDocs/DrawerNavGroup/examples/CustomNavGroupTitleContentExample.tsx, docs/src/componentDocs/DrawerNavGroup/examples/DrawerNavGroupCompositionExample.tsx, docs/src/componentDocs/DrawerNavGroup/examples/DrawerNavGroupExample.tsx, docs/src/componentDocs/DrawerNavGroup/examples/SpacingNavGroupsExample.tsx
=> Added onSurace font color for drawer examples

.github/workflows/blui-ci.yml, .github/workflows/firebase-hosting-pull-request.yml, eslint.config.mjs, packages/auth-workflows/jest.config.cjs, yarn.lock
=> pipeline fix

docs/src/app.tsx
Fixes # .
https://github.com/etn-ccis/blui-react-native/issues/125
- Updated landing page height issue by replacing 100% with 100vh
-
-
**Before**
**After**
-
-
=> Fixed dev doc landing page height issue

.husky/pre-commit.d/pre-check-code, docs/src/componentDocs/Drawer/examples/CustomizableDrawer.tsx, docs/src/componentDocs/Drawer/examples/Drawer.tsx, docs/src/componentDocs/Drawer/playground/PlaygroundPage.tsx, docs/src/componentDocs/Drawer/playground/sharedPropsConfig.ts, docs/src/componentDocs/DrawerNavGroup/playground/PlaygroundPage.tsx, docs/src/componentDocs/DrawerNavItem/examples/DrawerNavItem.tsx, docs/src/componentDocs/DrawerNavItem/examples/DrawerNavItemExample.tsx, docs/src/componentDocs/DrawerNavItem/examples/NestedNavItem.tsx, docs/src/componentDocs/DrawerNavItem/examples/NestedNavItemExample.tsx, docs/src/componentDocs/DrawerNavItem/examples/SelectingANavItem.tsx, docs/src/componentDocs/DrawerNavItem/examples/SelectingANavItemExample.tsx, docs/src/componentDocs/DrawerNavItem/playground/PlaygroundPage.tsx, docs/src/componentDocs/DrawerSubheader/examples/DrawerSubheader.tsx, docs/src/componentDocs/DrawerSubheader/examples/InteractiveDrawerSubheader.tsx
Fixes # .
https://github.com/etn-ccis/blui-react-native/issues/161
- Fixes for Drawer title space issue
-
-
-
**Before**
**After**
- cd docs -> yarn install -> yarn start
-
=> Drawer text space issue

docs/src/componentDocs/Chip/examples/ChipWithIconExample.tsx, docs/src/componentDocs/Chip/playground/PlaygroundPage.tsx, docs/src/index.css
Fixes #BLUI-6727 .
- Fix for the issues [86](https://github.com/etn-ccis/blui-react-native/issues/86) and [159](https://github.com/etn-ccis/blui-react-native/issues/159)
=> Fix for Chip and Collapsible header outline issue

docs/src/main.tsx
Fixes # .
https://github.com/etn-ccis/blui-react-native/issues/143
- Suppress the BackHandler warning on web
-
-
-
-
-
=> Fix BackHandler warning on web

docs/src/componentDocs/CollapsibleHeaderLayout/playground/PlaygroundPage.tsx, docs/src/componentDocs/DrawerFooter/examples/DrawerFooter.tsx, docs/src/componentDocs/Hero/playground/playgroundPage.tsx
Fixes #BLUI-6727 .
- Fix for the issue [120](https://github.com/etn-ccis/blui-react-native/issues/120)
- yarn start
=> Playground code snippet needs updated

docs/src/componentDocs/Chip/examples/ChipWithIcon.tsx
Fixes #BLUI-6725 .
-
-
-
-
-
-
=> Updated the icon size in code snippet

docs/src/shared/theme/ThemeExplorer.tsx
Fixes https://github.com/etn-ccis/blui-react-native/issues/201.
- updated ThemeExplorer.tsx
-
-
- Before: 
- 
- After : 
- 
- Go to theme overview section and check if its coming. 
-
=> fixed overview of theme

docs/src/componentDocs/AutoComplete/examples/AutoCompleteCustomTags.tsx, docs/src/componentDocs/AutoComplete/examples/AutoCompleteLimitTags.tsx, docs/src/componentDocs/AutoComplete/markdown/AutoCompleteAPIDocs.mdx, docs/src/componentDocs/AutoComplete/markdown/AutoCompleteExamples.mdx, docs/src/components/layout/SharedAppBar.tsx, examples/workflow/src/components/UserMenuComponent.tsx, packages/auth-workflows/src/screens/ResetPasswordScreen/ResetPasswordScreen.tsx, packages/component-library/docs/AutoComplete.md, packages/component-library/src/core/AutoComplete/AutoComplete.tsx, packages/component-library/src/core/AutoComplete/Autocomplete.test.tsx
Fixes # BLUI-6759 #170 
-Updated auto complete props names
- 
- cd docs 
- yarn start
-
=> Updated auto complete props names

packages/cli-templates/routing-typescript/template/ios/blankTemplate.xcodeproj/project.pbxproj, packages/component-library/package.json, packages/component-library/scripts/buildComponents.sh, packages/component-library/tsconfig.json, packages/component-library/yarn.lock
Fixes # .
- updated RN Components to ESM format
-
-
-
-
-
=> Converted RN Components to ESM format

docs/package.json, docs/src/componentDocs/Hero/examples/HeroWithChannelValueExample.tsx, docs/src/componentDocs/Hero/examples/HeroWithSecondaryIconExample.tsx, docs/src/componentDocs/IconSwitch/examples/IconSwitch.tsx, docs/src/componentDocs/IconSwitch/examples/IconSwitchExample.tsx, docs/src/componentDocs/IconSwitch/examples/IconSwitchWithIcon.tsx, docs/src/componentDocs/IconSwitch/examples/IconSwitchWithIconExample.tsx
Fixes #117 
- Updated icon switch example
-
-
-
-
-
=> Updated icon switch example in Dev Doc

packages/auth-workflows/CHANGELOG.md, packages/auth-workflows/package.json
=> Publish minor version 7.0.2

packages/auth-workflows/docs/language-support.md
Fixes #248  .
- Added documentation for how to override in-built translations
-
-
-
-
-
=> updated language support doc

packages/themes/scripts/buildThemes.sh, scripts/linkThemes.sh
Fixes # . updated build script to fix publishing
-
-
-
-
-
-
=> updated theme script for publishing

packages/auth-workflows/README.md, packages/component-library/MIGRATION-v8.md, packages/component-library/README.md, packages/progress-icons/README.md, packages/themes/README.md
=> update themes and component docs for expo

packages/auth-workflows/CHANGELOG.md, packages/component-library/CHANGELOG.md, packages/progress-icons/CHANGELOG.md, packages/themes/CHANGELOG.md
Fixes # .
- updated change log with todays date to publish.
-
-
-
-
-
=> updated changelog with date to realease

.github/workflows/blui-publish-auth-workflow.yml, .github/workflows/blui-publish-components.yml, .github/workflows/blui-publish-progress-icons.yml, .github/workflows/blui-publish-templates.yml
=> updated yml

packages/auth-workflows/package.json, packages/component-library/package.json, packages/progress-icons/package.json, packages/themes/package.json
=> pkg change

.github/workflows/blui-publish-auth-workflow.yml, .github/workflows/blui-publish-components.yml, .github/workflows/blui-publish-progress-icons.yml, .github/workflows/blui-publish-templates.yml
This reverts commit fa41fbc68e648396451d0da17654c8963d30a90c.
Fixes # .
-
-
-
-
-
-
=> Revert "Updated cli template dependency"

docs/src/markdownDocs/Overview.mdx
Fixes #blui-6875 .
- Fix for the [issue](https://github.com/etn-ccis/blui-react-native/issues/335)
-
-
Please confirm all items below have been addressed prior to requesting review:
=> Clean up links that still points to old repos

packages/component-library/src/core/IconSwitch/IconSwitch.tsx
Fixes #BLUI-6875 .
- Fix for the [issue](https://github.com/etn-ccis/blui-react-native/issues/349)
-
-
-
Please confirm all items below have been addressed prior to requesting review:
=> Icon Switch breaking in RN v0.80

.gitignore, eslint.config.mjs, packages/auth-workflows/package.json, packages/auth-workflows/src/screens/LoginScreen/LoginScreenBase.tsx, pnpm-lock.yaml
Fixes #BLUI-6999 .
- Patch version 8.0.1
-
-
-
Please confirm all items below have been addressed prior to requesting review:
=> Auth Workflow Package Patch Release 
